services:
  asellibot:
    image: "aselli_bot"
    build:
      context: .
    restart: always
    init: true
    volumes:
      - "./configs:/asellibot/configs"
    ports:
      - "88:88"
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    # This makes IPv6 easier; see below
    restart: always
    # Restart the updater after reboot
    volumes:
      - "./configs/cloudflare:/cloudflare"
    cap_add:
      - SETUID
        # Capability to change user ID; needed for using PUID
      - SETGID
        # Capability to change group ID; needed for using PGID
    cap_drop:
      - all
      # Drop all other capabilities
    read_only: true
    # Make the container filesystem read-only
    security_opt:
      - no-new-privileges:true
        # Another protection to restrict superuser privileges
    environment:
      - PUID=1000
        # Run the updater with user ID 1000
      - PGID=1000
        # Run the updater with group ID 1000
      - CF_API_TOKEN_FILE=/cloudflare/token.txt
        # Your Cloudflare API token
      - DOMAINS=aselli.it
        # Your domains (separated by commas)
      - PROXIED=true
        # Tell Cloudflare to cache webpages and hide your IP
      - UPDATE_ON_START=true
      - IP6_PROVIDER=none
